source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'ASCocoaCategory_Example', :exclusive => true do
  pod 'ASCocoaCategory', :path => '../'
end

target 'ASCocoaCategory_Tests', :exclusive => true do
  pod 'ASCocoaCategory', :path => '../'

  
end
